FROM nvidia/cuda:11.4.3-base-ubuntu20.04

LABEL maintainer='Michaël "e7d" Ferrand <michael@e7d.io>'

RUN apt-get update && \
    apt-get -y install git golang --no-install-recommends && \
    rm -r /var/lib/apt/lists/*
RUN export GOPATH=/go && \
    export PATH=$PATH:$GOPATH/bin && \
    go get -u github.com/mitranim/gow && \
    mv $GOPATH/bin/gow /usr/bin/gow

WORKDIR /go

EXPOSE 9202

CMD [ "gow", "run", "app.go" ]
