{
 "title": "NVIDIA SMI Graphs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "id",
    "label": "GPU",
    "query": "nvidiasmi_utilization_gpu_percent"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_utilization_gpu_percent{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} GPU"
    },
    {
     "expr": "avg_over_time(nvidiasmi_performance_state_int{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} State"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_utilization_memory_percent{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Memory"
    },
    {
     "expr": "avg_over_time(nvidiasmi_fb_memory_usage_used_bytes{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} FB Used"
    },
    {
     "expr": "avg_over_time(nvidiasmi_bar1_memory_usage_used_bytes{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Bar1 Used"
    }
   ]
  },
  {
   "title": "Encoder / Decoder",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_utilization_encoder_percent{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Encoder"
    },
    {
     "expr": "avg_over_time(nvidiasmi_utilization_decoder_percent{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Decoder"
    }
   ]
  },
  {
   "title": "Frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_clock_graphics_hertz{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Graphics"
    },
    {
     "expr": "avg_over_time(nvidiasmi_clock_sm_hertz{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} SM"
    },
    {
     "expr": "avg_over_time(nvidiasmi_clock_mem_hertz{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Memory"
    },
    {
     "expr": "avg_over_time(nvidiasmi_clock_video_hertz{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Video"
    }
   ]
  },
  {
   "title": "Temperature / Fan",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_gpu_temp_celsius{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Temp"
    },
    {
     "expr": "avg_over_time(nvidiasmi_fan_speed_percent{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Fan"
    }
   ]
  },
  {
   "title": "Power draw",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_power_draw_watts{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} Temp"
    }
   ]
  },
  {
   "title": "PCI Bus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nvidiasmi_pci_tx_util_bytes_per_second{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} TX"
    },
    {
     "expr": "avg_over_time(nvidiasmi_pci_rx_util_bytes_per_second{id=\"$id\"}[$interval])",
     "legendFormat": "{{name}} RX"
    }
   ]
  }
 ]
}